### ISSUE TITLE
ModuleNotFoundError: No module named 'flows'

### ISSUE THREAD

**Issue by Gokkulnath** [joeybose/Adversarial-Example-Games#1]
Hi ,

Interesting Work and thanks for releasing the code. I am having trouble running the experiment following the instructions provided. I guess either flows.py is missing or the dependency is not documented in Conda Environment. Can you help me get the flow module. Thanks in advance.

Error Trace: 
> Traceback (most recent call last):
>   File "momentum_iterative_attack.py", line 20, in <module>
>     from __init__ import data_and_model_setup, load_data, eval
>   File "~/Adversarial-Example-Games/attacks/__init__.py", line 7, in <module>
>     from attacks.autopgd_pt import APGDAttack
>   File "../attacks/__init__.py", line 11, in <module>
>     from classifiers import load_all_classifiers, load_list_classifiers, load_dict_classifiers
>   File "../classifiers/__init__.py", line 5, in <module>
>     from utils.utils import load_unk_model, ARCHITECTURES
>   File "../utils/utils.py", line 20, in <module>
>     from models.dcgan28 import DiscriminatorCNN28
>   File "../models/__init__.py", line 3, in <module>
>     from .ae_models import MnistVAE, CifarVAE, Mnistautoencoder
>   File "../models/ae_models.py", line 9, in <module>
>     from flows import *
> ModuleNotFoundError: No module named 'flows'

**Comment by joeybose** [comment]
Hi! Thanks for catching this. We indeed forgot to add this dependency. This dependency is strictly not needed for anything but as a quick fix I've added the flows directory to the main branch of the repo. Can you re-fork/pull the repo and see if it fixes your issue?

**Comment by Gokkulnath** [comment]
Thanks a lot for the quick response.  

**No module named 'flows' Error got Fixed.**  

Kindly request you to share  the pretrained_classifiers weights folder used.   I checked around in the repo and couldn't find any references to obtain the same .  Currently i get the following error.
I get "FileNotFoundError: [Errno 2] No such file or directory: '../pretrained_classifiers/mnist/ensemble_adv_trained/modelXX.pt'"  when i try reproduce the results.  Thanks in Advance.

**Comment by joeybose** [comment]
Hi, sorry for the delay in responding. We were trying to upload the models and because it's so large it took a bit more time. But, here is a google drive folder with the trained models: https://drive.google.com/drive/folders/15uOvqP4OVek8CADozGErxm8dcyi4zXJ3?usp=sharing

**Comment by Gokkulnath** [comment]
Thanks a lot @joeybose for the pretrained models. Really appreciate your help.  You can close the issue if you want to. 👍🏼
